INSERT INTO Especialidade VALUES(-1, 'SAJ - SERVIÇO DE ASSIST. JURÍDICA');
INSERT INTO Especialidade VALUES(-2, 'CONCILIARE');
INSERT INTO Especialidade VALUES(-3, 'LIBERTARE');
INSERT INTO Especialidade VALUES(-4, 'CONSEMMA');

INSERT INTO EtapaAtendimento VALUES(-1, 'AÇÃO INICIADA');
INSERT INTO EtapaAtendimento VALUES(-2, 'AGENDAR ATENDIMENTO');
INSERT INTO EtapaAtendimento VALUES(-3, 'ANÁLISE DO CASO');
INSERT INTO EtapaAtendimento VALUES(-4, 'DESISTÊNCIA');
INSERT INTO EtapaAtendimento VALUES(-5, 'ENTRADA DE RECURSO');
INSERT INTO EtapaAtendimento VALUES(-6, 'SOLICITAÇÃO DE DOCUMENTOS');
INSERT INTO EtapaAtendimento VALUES(-7, 'CANCELADO');
INSERT INTO EtapaAtendimento VALUES(-8, 'HABILITAR');
INSERT INTO EtapaAtendimento VALUES(-9, 'REVOGADO');

INSERT INTO PapelUsuario VALUES(-1, 'ADMINISTRADOR');
INSERT INTO PapelUsuario VALUES(-2, 'ALUNO');

INSERT INTO StatusUsuario VALUES(-1, 'ONLINE');
INSERT INTO StatusUsuario VALUES(-2, 'OFFLINE');

INSERT INTO TipoResponsavel VALUES(-1, 'RESPONSÁVEL NPJ');
INSERT INTO TipoResponsavel VALUES(-2, 'PROFESSOR');